name: ML Model Training

on:
  push:
    branches: [github_wfs_s3_mlflow]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './model_deployment1/requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./model_deployment1/requirements.txt

    - name: Set up PostgreSQL
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        # Install PostgreSQL
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib

        # Start PostgreSQL service
        sudo systemctl start postgresql.service

        # Create PostgreSQL user and database
        sudo -u postgres psql -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';"
        sudo -u postgres psql -c "CREATE DATABASE mlflow_db;"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mlflow_db TO $POSTGRES_USER;"

        # Update pg_hba.conf to allow password authentication
        sudo sed -i 's/local\s\+all\s\+all\s\+peer/local all all md5/g' /etc/postgresql/*/main/pg_hba.conf
        sudo systemctl restart postgresql.service

        # Verify user and database creation
        sudo -u postgres psql -c "\du"
        sudo -u postgres psql -c "\l"

    - name: Make workflow script executable
      run: chmod +x ./model_deployment1/train_workflow.sh

    - name: Train model
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        POSTGRES_URI: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/mlflow_db"
      run: |
        cd ./model_deployment1
        ./train_workflow.sh