name: ML Model Training

on:
  push:
    branches: [github_wfs_s3_mlflow]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./model_deployment1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './model_deployment1/requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up POSTGRESQL
      env:
        PGUSER: ${{ secrets.POSTGRES_USER }}
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo service postgresql start
        psql -U $PGUSER -c "CREATE DATABASE mlflow_db;"
        psql -U $PGUSER -d mlflow_db -c "CREATE USER mlflow_user WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"
        psql -U $PGUSER -d mlflow_db -c "GRANT ALL PRIVILEGES ON DATABASE mlflow_db TO mlflow_user;"

    # Ensure `train_workflow.sh` is executable
    - name: Make workflow.sh executable
      run: chmod +x train_workflow.sh

  
    #Set AWS credentials as environment variables & Run workflow
    - name: Set AWS credentials & Train model
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        POSTGRES_URI: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/mlflow_db"
      run: ./train_workflow.sh
    
    



