name: ML Model Training

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./model_deployment1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './model_deployment1/requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
      python -m train.py \
      --dataset1-loc "data/ratings.csv" \
      --dataset2-loc "data/movies.csv" \
      --embed-dim 16 \
      --lr .005 \
      --epochs 4




